menu:
  Home: /
  Archives: /archives

# gitment
gitment: false
gitment_owner:
gitment_repo:
gitment_client_id:
gitment_client_secret:

# disqus comment
disqus: true
disqus_shortname: gerwang-github-io

# google analytics
googleTrackId: UA-126826784-1

# Mathjax support
mathjax:
  enable: true,
  per_page: true
  src: //cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML

# auto excerpt
enable_excerpt: true
