menu:
  Home: /
  Archives: /archives
  Categories: /categories
  Tags: /tags

# gitment
gitment: false
gitment_owner:
gitment_repo:
gitment_client_id:
gitment_client_secret:

# disqus comment
disqus: true
disqus_shortname: gerwang-github-io

# google analytics
googleTrackId: UA-126826784-1
